export type Question = { id: string; label: string; type: 'short' | 'long' | 'single' | 'multiple' | 'rating' | 'yesno'; required: boolean; options?: string[] };
export type Survey = { id: string; title: string; description: string; category: string; status: 'active' | 'draft' | 'closed'; questions: Question[]; responseCount: number; allowPhotos: boolean; requireName: boolean; showOnBoard: boolean; coverImage?: string; closesAt?: string };
export type ResponseItem = { id: string; surveyId: string; surveyTitle: string; name: string; publicName?: string; contact?: string; avatar?: string; category: string; answers: Record<string, string | string[] | number>; photos: string[]; createdAt: string; status: string; featured: boolean; consent: boolean; kioskId: string; area: string; questions?: Question[] };
export type FeedbackItem = { id: string; name: string; publicName?: string; contact?: string; avatar: string; category: string; title: string; message: string; suggestion?: string; rating?: number; photos: string[]; status: string; consent?: boolean; published: boolean; kioskId: string; area: string; createdAt: string; requestId?: string; legacy?: boolean };
export type FeedbackPayload = { name: string; contact: string; avatar: string; category: string; title: string; message: string; suggestion?: string; rating?: number; consent: boolean; kioskId: string; area: string; requestId?: string };
export const categories = ['Safety', 'Quality', 'Design', 'Sport', 'Service', 'EV', 'Infotainment', 'Others'];
export const colors: Record<string, string> = { Safety: '#e96c6e', Quality: '#82b1e9', Design: '#9b91d9', Sport: '#e6a669', Service: '#7eb9a3', EV: '#a9bb77', Infotainment: '#cd94b9', Others: '#959eae' };
export const avatars = [{ id: 'default', icon: '🚗' }, { id: 'smile', icon: '🙂' }, { id: 'leaf', icon: '🌿' }, { id: 'sun', icon: '☀️' }, { id: 'heart', icon: '❤️' }, { id: 'star', icon: '⭐' }, { id: 'flower', icon: '🌻' }, { id: 'spark', icon: '✨' }, { id: 'wave', icon: '🌊' }, { id: 'mountain', icon: '⛰️' }];
export const statuses: Record<string, string> = { new: 'New', reviewed: 'In review', shortlisted: 'Shortlisted', adopted: 'Adopted', hidden: 'Archived' };
export const json = (data: unknown, method = 'POST') => ({ method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) });
export const uid = () => crypto.randomUUID();
export const fileUrl = (key?: string) => !key ? '' : /^[a-f0-9]{64}$/.test(key) ? `/api/files/${key}` : key;
export const date = (v?: string) => v ? new Date(v).toLocaleString('en-IN', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' }) : '';
export const answer = (v: any, type?: string) => v === undefined || v === '' || v === null || (Array.isArray(v) && !v.length) ? '—' : type === 'rating' ? `${v} / 5` : Array.isArray(v) ? v.join(', ') : String(v);
export const blank = (): Survey => ({ id: '', title: '', description: '', category: 'Design', status: 'draft', questions: [{ id: uid(), label: '', type: 'rating', required: true }], responseCount: 0, allowPhotos: true, requireName: true, showOnBoard: true });
export function template(kind: string): Survey {
 const s = blank(), q = (label: string, type: Question['type'], options?: string[], required = true): Question => ({ id: uid(), label, type, required, ...(options ? { options } : {}) });
 if (kind === 'service') return { ...s, title: 'Your service visit', description: 'Tell us about your recent service visit. Your feedback helps us take better care of you and your vehicle.', category: 'Service', questions: [q('How would you rate your service experience?', 'rating'), q('Was your vehicle ready when promised?', 'yesno'), q('What could we do better?', 'long', undefined, false)] };
 if (kind === 'product') return { ...s, title: 'Help shape the next drive', description: 'What works well, and what would you change? Share your observations and add a photo to show us.', category: 'Design', questions: [q('Which areas would you improve?', 'multiple', categories.slice(0,7)), q('What problem did you notice?', 'long'), q('How would you improve it?', 'long'), q('What benefit would that bring?', 'short', undefined, false)] };
 return { ...s, title: 'Your driving experience', description: 'A better drive starts with your perspective. Tell us about your experience—it takes about two minutes.', category: 'Safety', questions: [q('How would you rate your overall experience?', 'rating'), q('What stood out most?', 'single', ['Comfort & design', 'Safety', 'Performance', 'Technology', 'Service']), q('What could make your next drive better?', 'long'), q('Would you recommend this experience?', 'yesno')] };
}
