'use client';
import { useState, useEffect, useRef } from 'react';
import { Activity, ClipboardList, LayoutGrid, Monitor, ShieldCheck, BarChart3, Settings2, MapPin, Plus, Search, ArrowUpRight, ArrowRight, Camera, Clock, MessageSquare, Users, Copy, Pencil, CheckCircle2, X, LockKeyhole, WifiOff, Download, ListFilter } from 'lucide-react';
import { request, getPending, sendPending, removePending } from './offline';
import { Survey, ResponseItem, categories, colors, statuses, json, fileUrl, date, answer, blank, template } from './model';
import { Avatar, Empty, Modal } from './ui';
import Builder from './builder';
import Insights from './insights';
import ResponseFlow from './response-flow';
import RegisterSW from './register-sw';

export default function SurveyApp() {
 const [view,setView]=useState('surveys'),[surveys,setSurveys]=useState<Survey[]>([]),[board,setBoard]=useState<ResponseItem[]>([]),[responses,setResponses]=useState<ResponseItem[]>([]);
 const [session,setSession]=useState<{user:{email:string;displayName:string}|null;isAdmin:boolean}>({user:null,isAdmin:false});
 const [loading,setLoading]=useState(true),[online,setOnline]=useState(true),[error,setError]=useState(''),[toast,setToast]=useState('');
 const [search,setSearch]=useState(''),[category,setCategory]=useState('All categories'),[filterStatus,setFilterStatus]=useState('all'),[surveyFilter,setSurveyFilter]=useState('all'),[areaFilter,setAreaFilter]=useState('all');
 const [builder,setBuilder]=useState<Survey|null>(null),[detail,setDetail]=useState<ResponseItem|null>(null),[lightbox,setLightbox]=useState(''),[shareLink,setShareLink]=useState('');
 const [selected,setSelected]=useState<Survey|null>(null),[kiosk,setKiosk]=useState(false),[kioskId,setKioskId]=useState('K-01'),[area,setArea]=useState('Experience Zone'),[settings,setSettings]=useState(false),[clock,setClock]=useState('');
 const [pendingCount,setPendingCount]=useState(0),[queueError,setQueueError]=useState(''); const syncing=useRef(false),queryLoaded=useRef(false);
 const notify=(s:string)=>setToast(s);
 const refresh=async(quiet=false)=>{if(!quiet)setLoading(true);try{const [a,b,c]=await Promise.all([request('/api/surveys'),request('/api/board'),request('/api/session')]);setSurveys(a.surveys);setBoard(b.responses);setSession(c);setError('');localStorage.setItem('sd-survey-cache',JSON.stringify(a.surveys.filter((s:Survey)=>s.status==='active')));if(c.isAdmin){const d=await request('/api/responses');setResponses(d.responses);}else setResponses([]);if(!queryLoaded.current){queryLoaded.current=true;const p=new URLSearchParams(location.search);if(['admin','board','results'].includes(p.get('view')||''))setView(p.get('view')!);if(p.get('kiosk')){setKioskId(p.get('kiosk')!);localStorage.setItem('sd-kiosk-id',p.get('kiosk')!);setKiosk(true);}if(p.get('survey')){const s=a.surveys.find((s:Survey)=>s.id===p.get('survey'));if(s)setSelected(s);else setError('This survey is unavailable or has been archived.');}}}catch(e){setError((e as Error).message);if(!navigator.onLine){try{const cached:Survey[]=JSON.parse(localStorage.getItem('sd-survey-cache')||'[]');setSurveys(cached);const id=new URLSearchParams(location.search).get('survey');if(id&&!queryLoaded.current){setSelected(cached.find(s=>s.id===id)||null);queryLoaded.current=true;}}catch{}}}finally{setLoading(false);}};
 const syncQueue=async()=>{if(syncing.current||!navigator.onLine)return;syncing.current=true;try{const list=await getPending();for(const item of list){try{await sendPending(item);await removePending(item.id);notify('Your saved response has been sent.');setQueueError('');}catch(e){setQueueError((e as Error).message);break;}}setPendingCount((await getPending()).length);}catch{}finally{syncing.current=false;}};
 useEffect(()=>{setKioskId(localStorage.getItem('sd-kiosk-id')||'K-01');setArea(localStorage.getItem('sd-area')||'Experience Zone');setOnline(navigator.onLine);refresh();syncQueue();const tick=()=>setClock(new Date().toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',hour12:false}));tick();const timer=setInterval(()=>{tick();refresh(true);syncQueue();},30000);const connect=()=>{setOnline(navigator.onLine);if(navigator.onLine){refresh(true);syncQueue();}};window.addEventListener('online',connect);window.addEventListener('offline',connect);return()=>{clearInterval(timer);window.removeEventListener('online',connect);window.removeEventListener('offline',connect);};},[]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),5000);return()=>clearTimeout(t);},[toast]);
 useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape'){setLightbox('');setDetail(null);setSettings(false);setShareLink('');}};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[]);
 useEffect(()=>{if(view!=='admin'&&view!=='results')return;let t:ReturnType<typeof setTimeout>;const reset=()=>{clearTimeout(t);t=setTimeout(()=>{setView('surveys');setDetail(null);setBuilder(null);notify('Manager view closed after inactivity.');},180000);};reset();window.addEventListener('pointerdown',reset);window.addEventListener('keydown',reset);return()=>{clearTimeout(t);window.removeEventListener('pointerdown',reset);window.removeEventListener('keydown',reset);};},[view]);
 const navigate=(v:string)=>{setView(v);setSearch('');setCategory('All categories');setFilterStatus('all');history.replaceState({},'',v==='surveys'?'/':`/?view=${v}`);};
 const share=async(s:Survey)=>{const u=`${location.origin}/?survey=${s.id}`;try{await navigator.clipboard.writeText(u);notify('Survey link copied. Anyone with the link can respond.');}catch{setShareLink(u);}};
 const changeResponse=async(id:string,patch:Partial<ResponseItem>)=>{try{await request(`/api/responses/${id}`,json(patch,'PATCH'));await refresh(true);if(detail?.id===id)setDetail({...detail,...patch});notify('Response updated.');}catch(e){notify((e as Error).message);}};
 const visible=surveys.filter(s=>(category==='All categories'||s.category===category)&&(filterStatus==='all'||s.status===filterStatus)&&`${s.title} ${s.description}`.toLowerCase().includes(search.toLowerCase()));
 const filtered=responses.filter(r=>(category==='All categories'||r.category===category)&&(filterStatus==='all'||r.status===filterStatus)&&(surveyFilter==='all'||r.surveyId===surveyFilter)&&(areaFilter==='all'||r.area===areaFilter)&&`${r.id} ${r.name} ${r.contact||''} ${r.surveyTitle} ${Object.values(r.answers).join(' ')}`.toLowerCase().includes(search.toLowerCase()));
 const active=surveys.filter(s=>s.status==='active'&&(!s.closesAt||Date.parse(s.closesAt)>Date.now())).length;
 const summary=[{label:'Surveys open',value:active,foot:'Ready for your perspective',icon:ClipboardList},{label:'Responses collected',value:surveys.reduce((n,s)=>n+s.responseCount,0),foot:'Every voice counts',icon:MessageSquare},{label:'Photos on the board',value:board.reduce((n,r)=>n+r.photos.length,0),foot:'Experiences, in focus',icon:Camera}];
 const templates=[{kind:'drive',title:'Driving experience',text:'Ratings, highlights, and recommendations'},{kind:'service',title:'Service feedback',text:'A better visit starts with a little feedback'},{kind:'product',title:'Product improvements',text:'Observations, ideas, and supporting photos'}];
 if(selected)return <><RegisterSW/><ResponseFlow survey={selected} kiosk={kiosk} kioskId={kioskId} area={area} onClose={()=>{setSelected(null);history.replaceState({},'','/');refresh(true);}} onQueued={async()=>{setPendingCount((await getPending()).length);}}/></>;
 return <div className={`app-shell ${kiosk?'kiosk-shell':''}`}><RegisterSW/>
 <aside className="sidebar"><a href="/" className="brand" aria-label="Survey Drive home"><span className="brand-mark"><Activity size={25} strokeWidth={2.7}/></span><span><span className="brand-name">SURVEY<span>DRIVE</span></span><span className="brand-sub">EVERY VOICE. FORWARD.</span></span></a><div className="eyebrow nav-section-label">EXPERIENCE HUB</div>{[{id:'surveys',label:'Surveys',icon:ClipboardList},{id:'board',label:'Response board',icon:LayoutGrid}].map(n=><button className={`nav-item ${view===n.id?'active':''}`} onClick={()=>navigate(n.id)} key={n.id}><n.icon size={19}/>{n.label}{n.id==='surveys'&&<span>{active}</span>}</button>)}<button className={`nav-item ${kiosk?'active':''}`} onClick={()=>{setKiosk(!kiosk);notify(kiosk?'Kiosk mode off.':'Kiosk mode on. Responses reset after inactivity.');}}><Monitor size={19}/>Kiosk mode</button><div className="eyebrow nav-section-label">MANAGEMENT</div><button className={`nav-item ${view==='admin'?'active':''}`} onClick={()=>navigate('admin')}><ShieldCheck size={19}/>Manager view</button><button className={`nav-item ${view==='results'?'active':''}`} onClick={()=>navigate('results')}><BarChart3 size={19}/>Insights</button><div className="sidebar-footer"><span className="live-dot"/>{online?'Connected · live updates':'Offline · responses saved'}<div className="divider"/><p>Small observations.<br/><strong>Better experiences.</strong></p><span className="brand-sub">SURVEY DRIVE · V1.0</span></div></aside>
 <main className="workspace"><header className="topbar"><div className="breadcrumb">Experience hub <span>/</span><strong>{view==='surveys'?'Surveys':view==='board'?'Response board':view==='admin'?'Manager view':'Insights'}</strong></div><div className="topbar-actions"><span className="location"><MapPin size={13}/>{area}</span><span className="clock">{clock}</span><button className="icon-button" aria-label="Kiosk settings" onClick={()=>setSettings(true)}><Settings2 size={17}/></button></div></header><div className="content">
 {!online&&<div className="error-banner"><WifiOff size={17}/>You’re offline. Responses will be saved on this device and sent when the connection returns.</div>}{error&&online&&<div className="error-banner">{error}<button className="button ghost small" onClick={()=>refresh()}>Retry</button></div>}{pendingCount>0&&<div className="panel queue-banner"><Clock size={17}/><span>{pendingCount} response{pendingCount!==1?'s':''} waiting to sync. {queueError&&`Needs attention: ${queueError}`}</span><button className="button secondary small" onClick={()=>{setQueueError('');syncQueue();}}>Retry sync</button></div>}
 {view==='surveys'&&<><div className="page-header"><div><div className="eyebrow"><span className="live-dot"/>YOUR PERSPECTIVE MATTERS</div><h1 className="hero-title">Every voice.<br/><span>A better drive.</span></h1><p className="muted">Share what you see. Tell us what you think.<br/>Help shape the experiences that come next.</p></div><div className="hero-aside"><div className="hero-emblem"><Activity size={88} strokeWidth={1}/></div><span className="eyebrow">LISTEN. LEARN. IMPROVE.</span></div></div><div className="stats-grid">{summary.map(s=><div className="stat-card" key={s.label}><div className="stat-label">{s.label}<s.icon size={17}/></div><div className="stat-value">{String(s.value).padStart(2,'0')}</div><div className="stat-foot">{s.foot}</div></div>)}</div><div className="section-heading"><div><h2>Find your survey <span className="count-label">{String(visible.length).padStart(2,'0')}</span></h2><p className="muted">A few minutes of your time. A lasting difference.</p></div>{session.isAdmin&&<button className="button primary" onClick={()=>setBuilder(blank())}><Plus size={17}/>Create survey</button>}</div>
 <div className="toolbar"><div className="search-field"><Search size={17}/><input aria-label="Search surveys" placeholder="Search surveys…" value={search} onChange={e=>setSearch(e.target.value)}/></div><CategorySelect value={category} onChange={setCategory}/><div className="filter-pills">{['all','active','closed',...(session.isAdmin?['draft']:[])].map(s=><button className={`filter-chip ${filterStatus===s?'active':''}`} key={s} onClick={()=>setFilterStatus(s)}>{s==='all'?'All surveys':s==='active'?'Open now':s[0].toUpperCase()+s.slice(1)}</button>)}</div></div>
 {loading?<div className="survey-grid">{[1,2,3].map(i=><div className="skeleton" key={i}/>)}</div>:visible.length?<div className="survey-grid">{visible.map((s,i)=><SurveyCard key={s.id} survey={s} index={i} admin={session.isAdmin} onRespond={()=>{setSelected(s);history.replaceState({},'',`/?survey=${s.id}`);}} onEdit={()=>setBuilder(s)} onShare={()=>share(s)}/>)}</div>:<Empty icon={ClipboardList} title={surveys.length?'No surveys match your filters':'The next conversation starts here'} text={surveys.length?'Try another category or clear your search.':'New surveys will appear here as soon as the team opens them. Your perspective is always welcome.'}>{session.isAdmin?<button className="button primary" onClick={()=>setBuilder(template('drive'))}><Plus size={17}/>Start with a survey</button>:<button className="button secondary" onClick={()=>navigate('board')}>Explore the response board<ArrowRight size={15}/></button>}</Empty>}
 {session.isAdmin&&<div className="template-section"><div className="section-heading"><h2>A starting point for every conversation.</h2><span className="eyebrow">SURVEY TEMPLATES</span></div><div className="template-grid">{templates.map(t=><button className="template-card" key={t.kind} onClick={()=>setBuilder(template(t.kind))}><ClipboardList size={22}/><h3>{t.title}</h3><p className="muted">{t.text}</p><span className="row">Use template<ArrowUpRight size={15}/></span></button>)}</div></div>}<div className="board-footer"><ShieldCheck size={18}/><span>Your contact details stay private. Photos appear on the board only with your permission and team approval.</span><span className="eyebrow">YOUR VOICE COUNTS</span></div></>}
 {view==='board'&&<><div className="page-header"><div><div className="eyebrow"><span className="live-dot"/>COMMUNITY PERSPECTIVES</div><h1 className="hero-title">The response board<span>.</span></h1><p className="muted">Real experiences. Fresh perspectives. Progress you can see.</p></div><button className="button primary" onClick={()=>navigate('surveys')}>Share your experience<ArrowUpRight size={17}/></button></div><div className="toolbar"><div className="search-field"><Search size={17}/><input placeholder="Search responses…" aria-label="Search board" value={search} onChange={e=>setSearch(e.target.value)}/></div><CategorySelect value={category} onChange={setCategory}/></div><div className="board-grid">{board.filter(r=>(category==='All categories'||r.category===category)&&`${r.surveyTitle} ${Object.values(r.answers).join(' ')}`.toLowerCase().includes(search.toLowerCase())).map(r=><article className="response-card" key={r.id}><div className="row"><Avatar value={r.avatar}/><div className="grow"><strong>{r.publicName||r.name||'Anonymous'}</strong><div className="help-text">{r.surveyTitle}</div></div><span className="badge green">{statuses[r.status]||'New'}</span></div><div className="response-card-answer">{(r.questions||[]).slice(0,3).map(q=><div key={q.id}><span className="detail-label">{q.label}</span><p>{answer(r.answers[q.id],q.type)}</p></div>)}</div>{r.photos.length>0&&<div className="response-photos">{r.photos.map(p=><button key={p} onClick={()=>setLightbox(fileUrl(p))}><img src={fileUrl(p)} alt="Photo shared with this response"/></button>)}</div>}<div className="survey-card-footer"><span className="badge gray" style={{color:colors[r.category]}}>{r.category}</span><span className="help-text">{date(r.createdAt)}</span></div></article>)}</div>{!board.length&&<Empty icon={MessageSquare} title="Every story begins with a first response" text="Approved responses and photos will appear here. Join a survey to share your perspective."><button className="button primary" onClick={()=>navigate('surveys')}>Find a survey<ArrowRight size={17}/></button></Empty>}</>}
 {(view==='admin'||view==='results')&&(session.isAdmin?<><div className="page-header"><div><div className="eyebrow">SURVEY DRIVE / MANAGEMENT</div><h1 className="hero-title">{view==='admin'?'Keep the conversation moving.':'Turn feedback into progress.'}</h1><p className="muted">Create surveys, review photo responses, and put useful insights in focus.</p></div><div className="stack"><button className="button primary" onClick={()=>setBuilder(blank())}><Plus size={17}/>Create survey</button><a className="button ghost small" href="/signout-with-chatgpt?return_to=/" target="_top">Sign out</a></div></div><div className="stats-grid admin-stats">{[{label:'All responses',n:responses.length,status:'all'},{label:'Awaiting review',n:responses.filter(r=>r.status==='new').length,status:'new'},{label:'Shortlisted',n:responses.filter(r=>r.status==='shortlisted').length,status:'shortlisted'},{label:'Adopted',n:responses.filter(r=>r.status==='adopted').length,status:'adopted'}].map(s=><button className="stat-card" key={s.label} onClick={()=>{setFilterStatus(s.status);setView('admin');}}><div className="stat-label">{s.label}<ArrowUpRight size={16}/></div><div className="stat-value">{String(s.n).padStart(2,'0')}</div></button>)}</div><div className="tab-bar"><button className={`tab ${view==='admin'?'active':''}`} onClick={()=>setView('admin')}>Responses</button><button className={`tab ${view==='results'?'active':''}`} onClick={()=>setView('results')}>Insights</button><button className="tab" onClick={()=>navigate('surveys')}>Manage surveys<ArrowUpRight size={14}/></button></div>
 <div className="toolbar"><div className="search-field"><Search size={17}/><input placeholder="Name, contact, reference or answer…" aria-label="Search admin responses" value={search} onChange={e=>setSearch(e.target.value)}/></div><select className="select-input" aria-label="Select survey" value={surveyFilter} onChange={e=>setSurveyFilter(e.target.value)}><option value="all">All surveys</option>{surveys.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select><select className="select-input" aria-label="Response status" value={filterStatus} onChange={e=>setFilterStatus(e.target.value)}><option value="all">All statuses</option>{Object.entries(statuses).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select className="select-input" aria-label="Response area" value={areaFilter} onChange={e=>setAreaFilter(e.target.value)}><option value="all">All areas</option>{Array.from(new Set(responses.map(r=>r.area))).map(a=><option key={a}>{a}</option>)}</select><button className="button ghost small" onClick={()=>{setSearch('');setCategory('All categories');setFilterStatus('all');setSurveyFilter('all');setAreaFilter('all');}}>Reset</button></div>
 {view==='admin'?<div className="panel"><div className="panel-header"><h2>Collected responses <span className="count-label">{filtered.length}</span></h2><a className="button secondary small" href={`/api/export${surveyFilter==='all'?'':`?surveyId=${surveyFilter}`}`}><Download size={15}/>Export CSV</a></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Respondent</th><th>Survey / reference</th><th>Category</th><th>Photos</th><th>Status</th><th>Received</th><th/></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><div className="row"><Avatar value={r.avatar}/><div><strong>{r.name||'Anonymous'}</strong><span className="help-text block">{r.contact||'No contact shared'}</span></div></div></td><td><strong>{r.surveyTitle}</strong><span className="help-text block">{r.id.slice(0,8).toUpperCase()} · {r.kioskId}</span></td><td style={{color:colors[r.category]}}>{r.category}</td><td><span className="row"><Camera size={14}/>{r.photos.length}</span></td><td><select className="select-input small" aria-label={`Status for ${r.name||r.id}`} value={r.status} onChange={e=>changeResponse(r.id,{status:e.target.value})}>{Object.entries(statuses).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></td><td>{date(r.createdAt)}</td><td><button className="icon-button" aria-label={`View response ${r.id}`} onClick={()=>setDetail(r)}><ArrowUpRight size={17}/></button></td></tr>)}</tbody></table></div>{!filtered.length&&<Empty icon={MessageSquare} title="Ready for your first response" text="Publish a survey and share its link. Responses will arrive here, ready to review."/>}</div>:<Insights surveys={surveys} responses={filtered} onCategory={c=>{setCategory(c);setView('admin');}}/>}
 {!surveys.length&&<div className="template-section"><div className="section-heading"><h2>Start a meaningful conversation.</h2><span className="eyebrow">CHOOSE A TEMPLATE</span></div><div className="template-grid">{templates.map(t=><button className="template-card" key={t.kind} onClick={()=>setBuilder(template(t.kind))}><ClipboardList size={22}/><h3>{t.title}</h3><p className="muted">{t.text}</p><span className="row">Use template<ArrowUpRight size={15}/></span></button>)}</div></div>}</>:<div className="welcome-panel"><div className="empty-icon"><LockKeyhole size={31}/></div><div className="eyebrow">ADMIN ACCESS</div><h1>Room for better decisions.</h1><p className="muted">Sign in to create surveys, review photo responses,<br/>track feedback, and export your results.</p><a className="button primary" href="/signin-with-chatgpt?return_to=%2F%3Fview%3Dadmin" target="_top">Sign in with ChatGPT<ArrowUpRight size={17}/></a>{session.user&&<p className="help-text">{session.user.email} is not on the admin list. Use your approved admin account.</p>}<p className="help-text">Respondents can take a survey without signing in.</p></div>)}
 </div></main>
 {builder&&<Builder survey={builder} onClose={()=>setBuilder(null)} onSaved={(_,archived)=>{setBuilder(null);refresh();notify(archived?'Survey archived. Existing responses remain available.':'Survey saved. Share its link when you’re ready.');}}/>}
 {detail&&<Modal title="Response details" wide onClose={()=>setDetail(null)}><div className="row"><Avatar value={detail.avatar}/><div className="grow"><h2>{detail.name||'Anonymous'}</h2><p className="muted">{detail.contact||'No contact shared'}</p></div><span className="badge gray">{statuses[detail.status]}</span></div><div className="detail-grid">{[['Survey',detail.surveyTitle],['Reference',detail.id.slice(0,8).toUpperCase()],['Area / kiosk',`${detail.area} · ${detail.kioskId}`],['Received',date(detail.createdAt)]].map(([l,v])=><div className="detail-item" key={l}><span className="detail-label">{l}</span><strong>{v}</strong></div>)}</div>{(detail.questions||[]).map(q=><div className="answer-card" key={q.id}><span className="detail-label">{q.label}</span><p>{answer(detail.answers[q.id],q.type)}</p></div>)}<div className="photo-grid">{detail.photos.map(p=><button className="photo-thumb" key={p} onClick={()=>setLightbox(fileUrl(p))}><img src={fileUrl(p)} alt="Respondent attachment"/></button>)}</div><div className="divider"/><div className="row wrap">{Object.entries(statuses).map(([v,l])=><button className={`button small ${detail.status===v?'primary':'secondary'}`} key={v} onClick={()=>changeResponse(detail.id,{status:v})}>{l}</button>)}</div><div className="toggle-row"><div><strong>Show on response board</strong><p className="help-text">{detail.consent?'Respondent gave permission to share their response and photos.':'This respondent did not consent to public sharing.'}</p></div><button disabled={!detail.consent||detail.status==='hidden'} className={`button ${detail.featured?'secondary':'primary'}`} onClick={()=>changeResponse(detail.id,{featured:!detail.featured})}>{detail.featured?'Remove from board':'Approve for board'}</button></div></Modal>}
 {settings&&<Modal title="Kiosk settings" onClose={()=>setSettings(false)}><p className="muted">Label this station so the team knows where feedback comes from.</p><label className="form-field"><span className="form-label">Kiosk ID</span><input className="text-input" maxLength={40} value={kioskId} onChange={e=>setKioskId(e.target.value)}/></label><label className="form-field"><span className="form-label">Area</span><input className="text-input" maxLength={100} value={area} onChange={e=>setArea(e.target.value)}/></label><button className="button primary" onClick={()=>{const id=kioskId.trim()||'K-01',a=area.trim()||'Experience Zone';setKioskId(id);setArea(a);localStorage.setItem('sd-kiosk-id',id);localStorage.setItem('sd-area',a);setSettings(false);notify('Station settings saved on this device.');}}>Save settings<CheckCircle2 size={17}/></button></Modal>}
 {shareLink&&<Modal title="Share this survey" onClose={()=>setShareLink('')}><input className="text-input" readOnly value={shareLink} onFocus={e=>e.target.select()}/><p className="help-text">Select and copy the link to invite respondents.</p></Modal>}
 {lightbox&&<div className="modal-backdrop lightbox" role="dialog" aria-modal="true" aria-label="Photo preview" onClick={()=>setLightbox('')}><button className="icon-button" aria-label="Close preview"><X/></button><img src={lightbox} alt="Full size respondent photo"/></div>}
 {toast&&<div className="toast" role="status"><CheckCircle2 size={18}/>{toast}<button className="icon-button" aria-label="Dismiss message" onClick={()=>setToast('')}><X size={14}/></button></div>}
 </div>;
}
function CategorySelect({value,onChange}:{value:string;onChange:(c:string)=>void}){return <select className="select-input" aria-label="Filter category" value={value} onChange={e=>onChange(e.target.value)}><option>All categories</option>{categories.map(c=><option key={c}>{c}</option>)}</select>;}
function SurveyCard({survey:s,index,admin,onRespond,onEdit,onShare}:{survey:Survey;index:number;admin:boolean;onRespond:()=>void;onEdit:()=>void;onShare:()=>void}){const open=s.status==='active'&&(!s.closesAt||Date.parse(s.closesAt)>Date.now());return <article className="survey-card"><div className="survey-card-top"><span className="category-mark" style={{color:colors[s.category],backgroundColor:`${colors[s.category]}12`}}><Activity size={23}/></span><span className={`badge ${open?'green':'gray'}`}>{open&&<span className="live-dot"/>}{open?'Open for responses':s.status==='draft'?'Draft':'Closed'}</span></div>{s.coverImage&&<img className="survey-cover" src={fileUrl(s.coverImage)} alt={s.title}/>}<div className="survey-card-body"><div className="eyebrow" style={{color:colors[s.category]}}>{s.category}<span className="muted"> / {String(index+1).padStart(2,'0')}</span></div><h3>{s.title}</h3><p className="muted">{s.description}</p><div className="survey-meta"><span><Clock size={13}/>{Math.max(1,Math.round(s.questions.length*.4))} min</span><span><ListFilter size={13}/>{s.questions.length} questions</span>{s.allowPhotos&&<span><Camera size={13}/>Photos welcome</span>}</div></div><div className="survey-card-footer"><span className="help-text">{s.responseCount} response{s.responseCount!==1?'s':''}</span><button className="button primary small" disabled={!open} onClick={onRespond}>{open?'Take survey':s.status==='draft'?'Draft':'Closed'}<ArrowUpRight size={15}/></button></div>{admin&&<div className="survey-admin-actions"><button className="button ghost small" onClick={onEdit}><Pencil size={13}/>Edit survey</button><button className="button ghost small" disabled={s.status==='draft'} onClick={onShare}><Copy size={13}/>Share link</button></div>}</article>;}
